package com.tieutu.entities;
// Generated May 20, 2017 12:46:27 AM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", catalog = "store_manager")
public class Customer implements java.io.Serializable {

	private Integer id;
	private String fullname;
	private String birthOfDay;
	private String email;
	private String phoneNumber;
	private String address;
	private Set<Order> orders = new HashSet<Order>(0);

	public Customer() {
	}

	public Customer(String fullname) {
		this.fullname = fullname;
	}

	public Customer(String fullname, String birthOfDay, String email, String phoneNumber, String address,
			Set<Order> orders) {
		this.fullname = fullname;
		this.birthOfDay = birthOfDay;
		this.email = email;
		this.phoneNumber = phoneNumber;
		this.address = address;
		this.orders = orders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "fullname", nullable = false)
	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	@Column(name = "birth_of_day", length = 45)
	public String getBirthOfDay() {
		return this.birthOfDay;
	}

	public void setBirthOfDay(String birthOfDay) {
		this.birthOfDay = birthOfDay;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone_number", length = 45)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "address", length = 45)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

}
