package com.tieutu.entities;
// Generated May 20, 2017 12:46:27 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderDetail generated by hbm2java
 */
@Entity
@Table(name = "order_detail", catalog = "store_manager")
public class OrderDetail implements java.io.Serializable {

	private int id;
	private Items items;
	private Order order;
	private Date crDatetime;
	private Integer quantiy;

	public OrderDetail() {
	}

	public OrderDetail(int id, Items items, Order order, Date crDatetime) {
		this.id = id;
		this.items = items;
		this.order = order;
		this.crDatetime = crDatetime;
	}

	public OrderDetail(int id, Items items, Order order, Date crDatetime, Integer quantiy) {
		this.id = id;
		this.items = items;
		this.order = order;
		this.crDatetime = crDatetime;
		this.quantiy = quantiy;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "items_id", nullable = false)
	public Items getItems() {
		return this.items;
	}

	public void setItems(Items items) {
		this.items = items;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", nullable = false)
	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cr_datetime", nullable = false, length = 19)
	public Date getCrDatetime() {
		return this.crDatetime;
	}

	public void setCrDatetime(Date crDatetime) {
		this.crDatetime = crDatetime;
	}

	@Column(name = "quantiy")
	public Integer getQuantiy() {
		return this.quantiy;
	}

	public void setQuantiy(Integer quantiy) {
		this.quantiy = quantiy;
	}

}
