package com.tieutu.entities;
// Generated May 20, 2017 12:46:27 AM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Restaurant generated by hbm2java
 */
@Entity
@Table(name = "restaurant", catalog = "store_manager")
public class Restaurant implements java.io.Serializable {

	private Integer id;
	private String name;
	private String address;
	private String phoneNumber;
	private String description;
	private Set<Floor> floors = new HashSet<Floor>(0);
	private Set<Account> accounts = new HashSet<Account>(0);
	private Set<Floor> floors_1 = new HashSet<Floor>(0);
	private Set<Account> accounts_1 = new HashSet<Account>(0);

	public Restaurant() {
	}

	public Restaurant(String name, String address, String phoneNumber, String description) {
		this.name = name;
		this.address = address;
		this.phoneNumber = phoneNumber;
		this.description = description;
	}

	public Restaurant(String name, String address, String phoneNumber, String description, Set<Floor> floors,
			Set<Account> accounts, Set<Floor> floors_1, Set<Account> accounts_1) {
		this.name = name;
		this.address = address;
		this.phoneNumber = phoneNumber;
		this.description = description;
		this.floors = floors;
		this.accounts = accounts;
		this.floors_1 = floors_1;
		this.accounts_1 = accounts_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address", nullable = false)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "phone_number", nullable = false, length = 25)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "restaurant")
	public Set<Floor> getFloors() {
		return this.floors;
	}

	public void setFloors(Set<Floor> floors) {
		this.floors = floors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "restaurant")
	public Set<Account> getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Set<Account> accounts) {
		this.accounts = accounts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "restaurant")
	public Set<Floor> getFloors_1() {
		return this.floors_1;
	}

	public void setFloors_1(Set<Floor> floors_1) {
		this.floors_1 = floors_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "restaurant")
	public Set<Account> getAccounts_1() {
		return this.accounts_1;
	}

	public void setAccounts_1(Set<Account> accounts_1) {
		this.accounts_1 = accounts_1;
	}

}
