package com.tieutu.entities;
// Generated May 20, 2017 12:46:27 AM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tables generated by hbm2java
 */
@Entity
@Table(name = "tables", catalog = "store_manager")
public class Tables implements java.io.Serializable {

	private int id;
	private Floor floor;
	private String name;
	private byte quatityCustomer;
	private String description;
	private Set<Order> orders = new HashSet<Order>(0);

	public Tables() {
	}

	public Tables(int id, Floor floor, String name, byte quatityCustomer) {
		this.id = id;
		this.floor = floor;
		this.name = name;
		this.quatityCustomer = quatityCustomer;
	}

	public Tables(int id, Floor floor, String name, byte quatityCustomer, String description, Set<Order> orders) {
		this.id = id;
		this.floor = floor;
		this.name = name;
		this.quatityCustomer = quatityCustomer;
		this.description = description;
		this.orders = orders;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "floor_id", nullable = false)
	public Floor getFloor() {
		return this.floor;
	}

	public void setFloor(Floor floor) {
		this.floor = floor;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "quatity_customer", nullable = false)
	public byte getQuatityCustomer() {
		return this.quatityCustomer;
	}

	public void setQuatityCustomer(byte quatityCustomer) {
		this.quatityCustomer = quatityCustomer;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tables")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

}
